const ADICIONALES = {
    "124": {
        "m100": {
            "202205": {
                pBase: 4.98,
                acu21 /*(respecto pBase)*/: 0.21,
                fija: 2.20,
                acu9 /*(respecto pBase)*/: 0.09,
            },
            "202206": {
                pBase: 5.75,
                acu21 /*(respecto pBase)*/: 1.05,
                fija: 2.20,
                acu9: 0,
            },
            "202207": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202208": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202209": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202210": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202211": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202212": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202301": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202302": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202303": {
                pBase: 9.27,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202304": {
                pBase: 14.79,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            }
        },
        "p100": {
            "202205": {
                pBase: 5.73,
                acu21 /*(respecto pBase)*/: 0.21,
                fija: 2.53,
                acu9 /*(respecto pBase)*/: 0.09,
            },
            "202206": {
                pBase: 5.75,
                acu21 /*(respecto pBase)*/: 1.05,
                fija: 2.53,
                acu9: 0,
            },
            "202207": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202208": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202209": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202210": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202211": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202212": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202301": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202302": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202303": {
                pBase: 10.67,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202304": {
                pBase: 17.01,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            }
        }
    },
    "125": {
        "m100": {
            "202205": {
                pBase: 4.88,
                acu21 /*(respecto pBase)*/: 0.21,
                fija: 2.20,
                acu9 /*(respecto pBase)*/: 0.09,
            },
            "202206": {
                pBase: 5.63,
                acu21 /*(respecto pBase)*/: 1.05,
                fija: 2.20,
                acu9: 0,
            },
            "202207": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202208": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202209": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202210": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202211": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202212": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202301": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202302": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202303": {
                pBase: 9.14,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202304": {
                pBase: 14.57,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            }
        },
        "p100": {
            "202205": {
                pBase: 5.61,
                acu21 /*(respecto pBase)*/: 0.21,
                fija: 2.53,
                acu9 /*(respecto pBase)*/: 0.09,
            },
            "202206": {
                pBase: 6.48,
                acu21 /*(respecto pBase)*/: 1.05,
                fija: 2.53,
            },
            "202207": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202208": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202209": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202210": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202211": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202212": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202301": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202302": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202303": {
                pBase: 10.51,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            },
            "202304": {
                pBase: 16.76,
                mes: 0.00,
                acu21 /*(respecto pBase)*/: 0,
                fija: 0,
                acu9: 0,
            }
        }
    }
};

export default ADICIONALES